name: 'Stale Invite'
description: 'Add reviewers to your Pull Request when they get no traction'
inputs:
  token:
    description: 'Github personal token to add reviewers to pull request'
    required: false
    default: ${{ github.token }}
  reviewers:
    description: 'Comma separated list of reviewers'
    required: true
  days-until-stale:
    description: 'Age in days the pull request must be to be picked up by this action'
    required: true
  base-branch:
    description: 'Only run for pull requests onto the given branch'
    required: false
    default: ''
  ignore-updates:
    description: 'Use the creation age instead of last update age'
    required: false
    default: 'true'
  ignore-draft:
    decription: 'Ignore pull requests that are marked as draft'
    required: false
    default: 'true'

runs:
  using: 'node16'
  main: 'build/index.js'

branding:
  icon: 'user-plus'
  color: 'green'
